name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate posts-list.js
        id: generate_posts_list
        run: |
          POSTS_DIR="posts"
          POSTS_ARRAY_CONTENT=$(find "$POSTS_DIR" -maxdepth 1 -type f -name "*.md" | sort | sed 's|^posts/|    "posts/|g; s|\\.md|\\.md",|g; s/,$//')
          echo "const markdownFiles = [" > posts-list.js
          echo "$POSTS_ARRAY_CONTENT" >> posts-list.js
          echo "];" >> posts-list.js

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: secdevops-digest
          directory: ./